### ISSUE TITLE
How to Reproduce Results?

### ISSUE THREAD

**Issue by drcdr** [nick11roberts/XD#1]
I read through your arXiv preprint, and your approach and results seem quite interesting.  Thanks for posting your code; can you also provide some commands to reproduce the results in the paper?  I'm particularly interested in the FNO results (e.g. last 4 rows of Table 6 and 7), and would like to try both eval (e.g. if you have existing weights) and retraining on different PDEs (but can start with FNO-1d or FNO-2d). Thank you

**Comment by nick11roberts** [comment]
Thanks for reading our paper and checking out our code! We've added installation instructions and instructions+scripts to run the PDE experiments in `XD/chrysalis/FNO/`.
